export enum QUEUES {
  USER_QUEUE = 'user_queue',
  MARKETPLACE_QUEUE = 'marketplace_queue',
  KITCHEN_QUEUE = 'kitchen_queue',
  WAREHOUSE_QUEUE = 'warehouse_queue',
}

export enum INGREDIENT_MSG {
  CREATE_INGREDIENT = 'CREATE_INGREDIENT',
  GET_ONE_INGREDIENT_BY_NAME = 'GET_ONE_INGREDIENT_BY_NAME',
}

export enum INVENTORY_MSG {
  UPDATE_INVENTORY = 'UPDATE_INVENTORY',
  GET_INVENTORY = 'GET_INVENTORY',
  GET_ONE_INVENTORY_BY_INGREDIENT_ID = 'GET_ONE_INVENTORY_BY_INGREDIENT_ID',
}
