# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Build, Push and Deploy to DockerHub
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker Buildx para builds avanzados
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Paso 3: Autenticación en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 4: Incrementar semánticamente la versión y subir el nuevo tag
      - name: Bump version and push tag
        id: versioning
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true

      # Paso 5: Guardar el nuevo tag en la variable de entorno IMAGE_TAG
      - name: Set image tag
        run: echo "IMAGE_TAG=${{ steps.versioning.outputs.new_tag }}" >> $GITHUB_ENV

      # Paso 6: Construir y publicar la imagen Docker en Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
